version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: veilindm/todo-app-backend:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 1234
      DB_NAME: todo_db
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend # Use your local frontend folder
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app # Mount local code for live reload
      - /app/node_modules # Prevent overwriting node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables hot reload in Docker
    depends_on:
      - backend

volumes:
  db_data:
