apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-app
  namespace: uas-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
      containers:
      - name: be-app
        image: veilindm/todo-app-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: "1234"
        - name: DB_NAME
          value: todo_db
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"