apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
  namespace: uas-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - name: fe-app
        image: veilindm/todo-app-frontend:latest
        ports:
        - containerPort: 3000
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "3000"
          - name: DANGEROUSLY_DISABLE_HOST_CHECK
            value: "true"
          - name: WDS_SOCKET_PORT
            value: "0"
          - name: REACT_APP_API_URL
            value: "http://be-service:5000"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"